import { Yuji_Mai } from "next/font/google";
import "./globals.css";

import AuthProvider from "./AuthProvider.js";

import { AppProvider } from "./Context.js";

const yujiMai = Yuji_Mai({ subsets: ['latin'], weight: ['400'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
<<<<<<< HEAD
        className={`${yujiMai.className} antialiased w-screen overflow-hidden`}
=======
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full overflow-hidden`}
>>>>>>> 75a44478f9bb18d179930d8d031cbb51a63c9256
      >
        <AuthProvider>
          <AppProvider>
            {children}
          </AppProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
